





train loader: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25500/25500 [00:12<00:00, 1988.05it/s]
test loader:  72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 1613/2250 [00:00<00:00, 2001.07it/s]
load_data shapes torch.Size([25500, 4627]) torch.Size([2250, 4627]) torch.Size([25500, 100]) torch.Size([2250, 100])
[1,    34] train loss: nan
test loader: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2250/2250 [00:01<00:00, 2001.15it/s]
individual scalar training:   0%|                                                                                                                                                     | 0/100 [00:00<?, ?it/s]/export/raid1/home/kneel027/miniconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/loss.py:530: UserWarning: Using a target size (torch.Size([750])) that is different to the input size (torch.Size([750, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)                                                                                                                          | 0/100 [00:00<?, ?it/s]
individual scalar training:   0%|                                                                                                                                                     | 0/100 [00:01<?, ?it/s]
epochs:   1%|█▌                                                                                                                                                               | 1/100 [00:01<01:52,  1.14s/it]
[2,    34] train loss: nan
[2] test loss: nan
loss counter: 1
[3,    34] train loss: nan
[3] test loss: nan
loss counter: 2
[4,    34] train loss: nan
[4] test loss: nan
individual scalar training:   0%|                                                                                                                                                     | 0/100 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/export/raid1/home/kneel027/Second-Sight/scalar_experiments/scalar_LR.py", line 327, in <module>
    main()
  File "/export/raid1/home/kneel027/Second-Sight/scalar_experiments/scalar_LR.py", line 323, in main
    VM.train_c_seperate(train, test)
  File "/export/raid1/home/kneel027/Second-Sight/scalar_experiments/scalar_LR.py", line 274, in train_c_seperate
    self.model.load_state_dict(torch.load("scalar_space_models/model_z_" + str(m) + ".pt"))
  File "/export/raid1/home/kneel027/miniconda3/envs/ldm/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/export/raid1/home/kneel027/miniconda3/envs/ldm/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/export/raid1/home/kneel027/miniconda3/envs/ldm/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'scalar_space_models/model_z_0.pt'